#!/bin/bash

rm -Rf "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_dashboards"
cp -r "${MFMODULE_HOME}/config/grafana_dashboards" "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/"
if test -d /etc/metwork.config.d/mfadmin/grafana_dashboards; then
    N=$(ls /etc/metwork.config.d/mfadmin/grafana_dashboards 2>/dev/null |wc -l)
    if test "${N}" -gt 0; then
        cp -f /etc/metwork.config.d/mfadmin/grafana_dashboards/* "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_dashboards/"
    fi
fi
rm -Rf "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning"
mkdir -p "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/datasources"
mkdir -p "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/dashboards"
cat "${MFMODULE_HOME}/config/grafana_provisioning/datasources/datasource.yaml" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/datasources/datasource.yaml"
cat "${MFMODULE_HOME}/config/grafana_provisioning/dashboards/dashboard.yaml" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/dashboards/dashboard.yaml"

cat "${MFMODULE_HOME}/config/grafana.ini" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana.ini"


mkdir -p "${MFMODULE_RUNTIME_HOME}/tmp/www"
cat "${MFMODULE_HOME}/config/www/index.html" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/www/index.html"
cat "${MFMODULE_HOME}/config/www/index.css" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/www/index.css"
cp -rf "${MFMODULE_HOME}/config/www/images" "${MFMODULE_RUNTIME_HOME}/tmp/www/"

rm -f "${MFMODULE_RUNTIME_HOME}/tmp/grafana.sock"
if test -s "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/grafana.ini"; then
    exit 0
else
    exit 1
fi
