#!/bin/bash

export KIBANA_HOME="${MFMODULE_RUNTIME_HOME}/var/kibana"

if test -d /etc/metwork.config.d/mfadmin/kibana_dashboards; then
    N=$(ls /etc/metwork.config.d/mfadmin/kibana_dashboards 2>/dev/null |wc -l)
    if test "${N}" -gt 0; then
        cp -f /etc/metwork.config.d/mfadmin/kibana_dashboards/* "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/kibana_dashboards/"
    fi
fi

cat "${MFMODULE_HOME}/config/kibana.conf" |envtpl --reduce-multi-blank-lines >"${KIBANA_HOME}/config/kibana.yml"
rm -f "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/kibana"
ln -s "${KIBANA_HOME}/config" "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/kibana"

if test -s "${KIBANA_HOME}/config/kibana.yml"; then
    exit 0
else
    exit 1
fi
