#!/bin/bash

rm -Rf "${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning"
mkdir -p "${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/datasources"
mkdir -p "${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/dashboards"
cat "${MODULE_HOME}/config/grafana_provisioning/datasources/datasource.yaml" |envtpl >"${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/datasources/datasource.yaml"
cat "${MODULE_HOME}/config/grafana_provisioning/dashboards/dashboard.yaml" |envtpl >"${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana_provisioning/dashboards/dashboard.yaml"

cat "${MODULE_HOME}/config/grafana.ini" |envtpl >"${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana.ini"

"${MODULE_HOME}/opt/monitoring/opt/grafana/bin/grafana-cli" -d admin reset-admin-password --config "${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana.ini" --homepath "${MODULE_HOME}/opt/monitoring/opt/grafana" "${MFADMIN_GRAFANA_ADMIN_PASSWORD}"
if test -s "${MODULE_RUNTIME_HOME}/tmp/config_auto/grafana.ini"; then
    exit 0
else
    exit 1
fi
