BINS=before_start_influxdb before_start_grafana _wait_grafana.py _wait_influxdb.py _provision_home_dashboard.py

include root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFCOM_HOME)/share/startup_scripts_profiles.mk
