{
 "title": "mfdata",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "fullres,medres,lowres" },
   {
    "name": "host",
    "query": "show tag values FROM \"mem\" with key=\"host\""
   },
   {
    "name": "plugin",
    "query": "show tag values FROM \"number_of_processed_files\" with key=\"plugin\""
   },
   {
    "name": "step",
    "query": "show tag values FROM \"number_of_processed_files\" with key=\"step\" where \"plugin\" =~ /^$plugin$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Maximum number of files by directory (cumulated graph) [not filtered by plugin/step]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "directory_name" ], "type": "tag" }
     ],
     "measurement": "var_in_files",
     "query": "SELECT mean(\"file_count\") FROM \"$resolution\".\"var_in_files\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata' AND \"directory_name\" != 'trash' AND \"directory_name\" != 'tmp') AND $timeFilter GROUP BY time($__interval), \"directory_name\"",
     "select": [
      [
       { "params": [ "file_count_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "directory_name", "operator": "!=", "value": "trash" },
      { "condition": "AND", "key": "directory_name", "operator": "!=", "value": "tmp" }
     ]
    }
   ]
  },
  {
   "title": "Sum of files processed by hour (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "number_of_processed_files",
     "select": [
      [
       { "params": [ "value_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Sum of files sizes processed by hour (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "bytes_of_processed_files",
     "select": [
      [
       { "params": [ "value_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Sum of files processed with error status by hour (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "number_of_processing_errors",
     "select": [
      [
       { "params": [ "value_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of batches processed by hour (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "number_of_processed_batches",
     "select": [
      [
       { "params": [ "value_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of batches processed with error status by hour (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "number_of_processed_batches_error",
     "select": [
      [
       { "params": [ "value_sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Mean duration of individual file processing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processing_file_timer",
     "select": [
      [
       { "params": [ "mean_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Mean duration of batch file processing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processing_batch_timer",
     "select": [
      [
       { "params": [ "mean_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfdata" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum memory usage (cumulated graph) [not filtered by step]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_mem_percent ($tag_host, $tag_plugin)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" }
     ],
     "measurement": "metwork_module",
     "query": "SELECT max(\"mem_percent_max\") FROM \"$resolution\".\"metwork_module\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata') AND $timeFilter GROUP BY time($__interval), \"host\", \"plugin\"",
     "select": [
      [
       { "params": [ "mem_percent_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  },
  {
   "title": "Maximum cpu usage (100% = 1core) (cumulated graph) [not filtered by step]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_cpu_usage ($tag_host, $tag_plugin)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" }
     ],
     "measurement": "metwork_module",
     "query": "SELECT max(\"cpu_percent_max\") FROM \"$resolution\".\"metwork_module\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata') AND $timeFilter GROUP BY time($__interval), \"host\", \"plugin\"",
     "select": [
      [
       { "params": [ "cpu_percent_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  }
 ]
}