{
 "title": "mfserv",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "fullres,medres,lowres" },
   {
    "name": "host",
    "query": "show tag values FROM \"request_counter\" with key=\"host\""
   },
   {
    "name": "plugin",
    "query": "show tag values FROM \"request_counter\" with key=\"plugin\""
   },
   {
    "name": "app",
    "query": "show tag values FROM \"request_counter\" with key=\"app\" where \"plugin\" =~ /^$plugin$/"
   },
   {
    "name": "status_code",
    "query": "show tag values FROM \"request_counter\" with key=\"status_code\""
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (maximum on the period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of requests processed by nginx per second (cumulated graph by host) [not filtered by plugin/app/status]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "requests_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nginx",
     "query": "SELECT non_negative_derivative(max(\"requests_max\"), 1s) FROM \"$resolution\".\"nginx\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfserv') AND $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "requests_sum" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  },
  {
   "title": "Number of active connections on nginx (cumulated graph by host) [not filtered by plugin/app/status_code]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "requests_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nginx",
     "query": "SELECT max(\"active_max\") FROM \"$resolution\".\"nginx\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfserv') AND $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "requests_sum" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  },
  {
   "title": "Number of (dynamic) requests per second processed by plugins (cumulated graph)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "app" ], "type": "tag" },
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "request_counter",
     "query": "SELECT 0.1 * mean(\"value_mean\") FROM \"$resolution\".\"request_counter\" WHERE (\"host\" =~ /^$host$/ AND \"plugin\" =~ /^$plugin$/ AND \"app\" =~ /^$app$/ AND \"type\" = 'dynamic' AND \"status_code\" =~ /^$status_code$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"plugin\", \"app\", \"status_code\"",
     "select": [
      [
       { "params": [ "value_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "dynamic" }
     ]
    }
   ]
  },
  {
   "title": "Mean execution time of (dynamic) requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "app" ], "type": "tag" },
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "request_timer",
     "query": "SELECT mean(\"file_count\") FROM \"$resolution\".\"var_in_files\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata' AND \"directory_name\" != 'trash' AND \"directory_name\" != 'tmp') AND $timeFilter GROUP BY time($__interval), \"directory_name\"",
     "select": [
      [
       { "params": [ "mean_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "dynamic" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^$status_code$/" }
     ]
    }
   ]
  },
  {
   "title": "Max execution time of (dynamic) requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "app" ], "type": "tag" },
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "request_timer",
     "query": "SELECT mean(\"file_count\") FROM \"$resolution\".\"var_in_files\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata' AND \"directory_name\" != 'trash' AND \"directory_name\" != 'tmp') AND $timeFilter GROUP BY time($__interval), \"directory_name\"",
     "select": [
      [
       { "params": [ "upper_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "dynamic" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^$status_code$/" }
     ]
    }
   ]
  },
  {
   "title": "cumulative mfserv max memory usage [not filtered by app/status_code]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_mem_usage ($tag_host, $tag_plugin)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" }
     ],
     "measurement": "metwork_module",
     "query": "SELECT mean(\"file_count\") FROM \"$resolution\".\"var_in_files\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata' AND \"directory_name\" != 'trash' AND \"directory_name\" != 'tmp') AND $timeFilter GROUP BY time($__interval), \"directory_name\"",
     "select": [
      [
       { "params": [ "mem_percent_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  },
  {
   "title": "cumulative mfserv max cpu usage  (100% = 1 core) [not filtered by app/status_code]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_cpu_usage ($tag_host, $tag_plugin)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" }
     ],
     "measurement": "metwork_module",
     "query": "SELECT mean(\"file_count\") FROM \"$resolution\".\"var_in_files\" WHERE (\"host\" =~ /^$host$/ AND \"module\" = 'mfdata' AND \"directory_name\" != 'trash' AND \"directory_name\" != 'tmp') AND $timeFilter GROUP BY time($__interval), \"directory_name\"",
     "select": [
      [
       { "params": [ "cpu_percent_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "plugin", "operator": "=~", "value": "/^$plugin$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "mfserv" }
     ]
    }
   ]
  }
 ]
}