{
 "title": "redis",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "fullres,medres,lowres" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "module",
    "query": "SHOW TAG VALUES WITH KEY = \"module\""
   }
  ]
 },
 "panels": [
  {
   "title": "Number of redis keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "mean_keys_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis_keyspace",
     "query": "SELECT mean(\"keys_mean\") FROM \"$resolution\".\"[[resolution]]_redis_keyspace\" WHERE $timeFilter AND \"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "keys_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max_keys_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis_keyspace",
     "query": "SELECT max(\"keys_max\") FROM \"$resolution\".\"[[resolution]]_redis_keyspace\" WHERE $timeFilter AND \"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "keys_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of expirable redis keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "mean_expires_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis_keyspace",
     "query": "SELECT mean(\"expires_mean\") FROM \"$resolution\".\"[[resolution]]_redis_keyspace\" WHERE $timeFilter AND \"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "keys_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max_expires_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis_keyspace",
     "query": "SELECT max(\"expires_max\") FROM \"$resolution\".\"[[resolution]]_redis_keyspace\" WHERE $timeFilter AND \"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "keys_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage relative to maximum configured (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis",
     "query": "SELECT 100.0 * max(\"used_memory_max\") / max(\"maxmemory_mean\") FROM \"fullres_redis\" WHERE $timeFilter GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "used_memory_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "maxmemory_mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "mean_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis",
     "query": "SELECT 100.0 * mean(\"used_memory_mean\") / max(\"maxmemory_mean\") FROM \"fullres_redis\" WHERE $timeFilter GROUP BY time($__interval), \"module\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "used_memory_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "maxmemory_mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of command processed by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullres_redis",
     "query": "SELECT non_negative_derivative(max(\"total_commands_processed_max\"), 10s) FROM \"$resolution\".\"[[resolution]]_redis\" WHERE (\"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"module\" fill(null)",
     "select": [
      [
       { "params": [ "total_commands_processed_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" }
     ]
    }
   ]
  }
 ]
}