{
 "title": "System Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "fullres,medres,lowres" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (maximum on the period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Load Average by core",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT MAX(mean_load1_per_core) FROM (SELECT max(\"load1_max\")/mean(\"n_cpus_mean\") AS mean_load1_per_core FROM \"$resolution\".\"system\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), host fill(null)) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SWAP usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"swap\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage (whole server)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"usage_active_max\") FROM \"$resolution\".\"cpu\" WHERE (\"host\" =~ /^$host$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage (single core)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT min(\"usage_idle_min\") * -1 + 100 FROM \"$resolution\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT max(\"total_max\") FROM \"$resolution\".\"processes\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT max(\"total_threads_max\") FROM \"$resolution\".\"processes\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean_total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "System metrics (all hosts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Load by cpu core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "load by cpu core" }
   ],
   "targets": [
    {
     "alias": "mean_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1_mean\")/mean(\"n_cpus_mean\") FROM \"$resolution\".\"system\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), host fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT max(\"load1_max\")/mean(\"n_cpus_mean\") FROM \"$resolution\".\"system\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), host fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent_mean\") FROM \"$resolution\".\"mem\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "mean_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"mem\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"disk\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"swap\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage (whole server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_active_max\") FROM \"$resolution\".\"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "mean_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_active_mean\") FROM \"$resolution\".\"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage (single core)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_active_max\") FROM \"$resolution\".\"cpu\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean/Max number of processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT max(\"total_max\") FROM \"$resolution\".\"processes\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "mean_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT mean(\"total_mean\") FROM \"$resolution\".\"processes\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "mean_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean/Max number of threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "max_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT max(\"total_threads_max\") FROM \"$resolution\".\"processes\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "max_total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "mean_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT mean(\"total_threads_mean\") FROM \"$resolution\".\"processes\" WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "min_total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detailled system metrics for host $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT max(\"used_percent_max\") FROM \"$resolution\".\"disk\" WHERE (\"host\" = '$host') AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "max_used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$host" }
       ]
      }
     ]
    },
    {
     "title": "max CPU usage for $host (whole server)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "max_$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT max(\"usage_iowait_max\") AS \"iowait\", max(\"usage_guest_max\") AS \"guest\", max(\"usage_guest_nice_max\") AS \"guest_nice\", max(\"usage_irq_max\") AS \"irq\", max(\"usage_nice_max\") AS \"nice\", max(\"usage_softirq_max\") AS \"softirq\", max(\"usage_steal_max\") AS \"steal\", max(\"usage_system_max\") AS \"system\", max(\"usage_user_max\") AS \"user\" FROM \"$resolution\".\"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "max_usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "guest" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "guest_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "nice" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "steal" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "user" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "mean number of processes for $host (cumulative graph)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "mean_$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fullres_processes",
       "query": "SELECT mean(\"blocked_mean\") AS \"blocked\", mean(\"dead_mean\") AS \"dead\", mean(\"idle_mean\") AS \"idle\", mean(\"paging_mean\") AS \"paging\", mean(\"running_mean\") AS \"running\", mean(\"sleeping_mean\") AS \"sleeping\", mean(\"stopped_mean\") AS \"stopped\", mean(\"unknown_mean\") AS \"unknown\", mean(\"zombies_mean\") AS \"zombies\" FROM \"$resolution\".\"processes\" WHERE $timeFilter  AND \"host\" =~ /^$host$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "blocked_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "dead_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "idle_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "paging_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "running_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "sleeping_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "stopped_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "unknown_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "zombies_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "mean CPU usage for $host (whole server)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "mean_$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_iowait_mean\") AS \"iowait\", mean(\"usage_guest_mean\") AS \"guest\", mean(\"usage_guest_nice_mean\") AS \"guest_nice\", mean(\"usage_irq_mean\") AS \"irq\", mean(\"usage_nice_mean\") AS \"nice\", mean(\"usage_softirq_mean\") AS \"softirq\", mean(\"usage_steal_mean\") AS \"steal\", mean(\"usage_system_mean\") AS \"system\", mean(\"usage_user_mean\") AS \"user\" FROM \"$resolution\".\"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "max_usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "guest" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "guest_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "nice" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "steal" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "max_usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "user" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}