{
 "title": "telegraf",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "fullres,medres,lowres" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "module",
    "query": "SHOW TAG VALUES WITH KEY = \"module\""
   }
  ]
 },
 "panels": [
  {
   "title": "Number of gathered metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_agent",
     "query": "SELECT non_negative_derivative(max(\"total_commands_processed_max\"), 10s) FROM \"$resolution\".\"[[resolution]]_redis\" WHERE (\"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"module\" fill(null)",
     "select": [
      [
       { "params": [ "metrics_gathered_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" }
     ]
    }
   ]
  },
  {
   "title": "Metrics write time on influxdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "max_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT max(\"write_time_ns_max\") FROM \"$resolution\".\"internal_write\" WHERE (\"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ AND \"output\" = 'influxdb') AND $timeFilter GROUP BY time($__interval), \"host\", \"module\" fill(null)",
     "select": [
      [
       { "params": [ "write_time_ns_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "output", "operator": "=", "value": "influxdb" }
     ]
    },
    {
     "alias": "mean_[[tag_host]]_[[tag_module]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT mean(\"write_time_ns_mean\") FROM \"$resolution\".\"internal_write\" WHERE (\"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ AND \"output\" = 'influxdb') AND $timeFilter GROUP BY time($__interval), \"host\", \"module\" fill(null)",
     "select": [
      [
       { "params": [ "write_time_ns_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "output", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "RSS size of telegraf process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "rss_max $tag_host $tag_module",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "% cpu usage of telegraf process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu_usage_max $tag_host $tag_module",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  }
 ]
}