server:
  http_listen_port: {{MFADMIN_PROMTAIL_HTTP_PORT}}
  grpc_listen_port: 0

positions:
  filename: {{MFMODULE_RUNTIME_HOME}}/tmp/promtail/positions.yaml

clients:
  - url: http://localhost:{{MFADMIN_LOKI_HTTP_PORT}}/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: {{LOGPROXY_LOG_DIRECTORY}}/tmp/promtail/*log
