apiVersion: 1

datasources:
- name: influxdb
  type: influxdb
  access: proxy
  url: http://127.0.0.1:{{MFADMIN_INFLUXDB_HTTP_PORT}}
  database: metrics
  isDefault: true
  editable: false
- name: es_nginx
  type: elasticsearch
  access: proxy
  database: "[nginx-]YYYY.MM.DD"
  url: http://127.0.0.1:{{MFADMIN_ELASTICSEARCH_HTTP_PORT}}
  jsonData:
    interval: Daily
    timeField: "@timestamp"
    esVersion: 60
- name: es_mflog
  type: elasticsearch
  access: proxy
  database: "[mflog-]YYYY.MM.DD"
  url: http://127.0.0.1:{{MFADMIN_ELASTICSEARCH_HTTP_PORT}}
  jsonData:
    interval: Daily
    timeField: "timestamp"
    esVersion: 60
- name: loki
  type: loki
  url: http://127.0.0.1:{{MFADMIN_LOKI_HTTP_PORT}}
